### ISSUE TITLE
[RDK] Due to m_Compositor not initialized resulting Segmentation fault

### ISSUE THREAD

**Issue by dongfengweixiao** [toyota-connected/ivi-homescreen#111]
agl branch

https://github.com/toyota-connected/ivi-homescreen/blob/98c82158c5ad48220393b39e3cb8206b08166f99/shell/wayland/display.cc#LL172C66-L172C66

**Comment by jwinarske** [comment]
What repo/commit are you testing with?

For AGL this is the authoritative repo, which has recent commits:
https://github.com/toyota-connected/ivi-homescreen/tree/agl

I cherry-pick from here to our internal `main`.

I do think Marius broke multiple output with recent commit, haven't had time to confirm.

**Comment by jwinarske** [comment]
Sorry I missed the commit.  This is on system without AGL compositor, or with?  it looks like without.

I am planning to cherry-pick AGL ophans into internal `main` branch.  It would be caught here.

For AGL you would want to include their changes from meta-agl-flutter:
https://gerrit.automotivelinux.org/gerrit/gitweb?p=AGL/meta-agl-devel.git;a=tree;f=meta-agl-flutter;h=f9f69082dbe163c1182c4e1c51120f3c77cb32ca;hb=HEAD

Also see how they run/start an app.

**Comment by jwinarske** [comment]
Also try equivalent CLI sequence since you're using single view and see if you get a repro:
```
--c --a=31 --f --b=/usr/share/flutter/gallery --no-serve-devtools --d
```

There is an upcoming OSS release that has a number of fixes as well as ivi-shell support.

**Comment by jwinarske** [comment]
@dongfengweixiao ping

**Comment by jwinarske** [comment]
Thanks for the follow-up.
