### ISSUE TITLE
How to position homescreen in center or screen?

### ISSUE THREAD

**Issue by emanuel-th** [toyota-connected/ivi-homescreen#131]
Hi, we have a setup where homescreen runs with a smaller dimensions than the screen.

Previously we used b18a478df377f9ed34e6aaaf364a504961c4e582 (sumo branch).
There we called:
`homescreen --f --w=<width> --h=<height> --a=/path/to/flutter_assets`
This starts homescreen centered in the screen.

Now after switching to kirkstone with a3113ea6b6df4ccdc4e1c057e41128cc586dc0c9 this does not work anymore.
As soon as --f is used, its full screen, width and heigth are ignored.
As far as I can see you cannot give margins or positions for homescreen.

Without --f homescreen has the dimensions as specified with --w and --h but at a random position within the screen.

Is there any way to get it centered?

**Comment by jwinarske** [comment]
@emanuel-th Using Wayland XDG client x, y is not an option.  You can position an absolute window location using ivi-shell or preferably the AGL-compositor.  For fullscreen bordering options that's not currently supported.  It can be added by turning Flutter View into a sub-surface.  This would allow sub-set position with a fixes background.  The background could be full field, blur effect, or other image.
