### ISSUE TITLE
I can't find libflutter_engine.so

### ISSUE THREAD

**Issue by ehjoon** [toyota-connected/ivi-homescreen#132]
After building flutter application as guide, I can't find libflutter_engine.so

$ find build
build
build/flutter_assets
build/flutter_assets/NOTICES.Z
build/flutter_assets/shaders
build/flutter_assets/shaders/ink_sparkle.frag
build/flutter_assets/isolate_snapshot_data
build/flutter_assets/AssetManifest.bin
build/flutter_assets/.last_build_id
build/flutter_assets/AssetManifest.json
build/flutter_assets/kernel_blob.bin
build/flutter_assets/fonts
build/flutter_assets/fonts/MaterialIcons-Regular.otf
build/flutter_assets/packages
build/flutter_assets/packages/cupertino_icons
build/flutter_assets/packages/cupertino_icons/assets
build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
build/flutter_assets/vm_snapshot_data
build/flutter_assets/FontManifest.json
build/snapshot_blob.bin.d

That might be out of scope you can guide, I would appreciate it if you could kindly guide me.

**Comment by jwinarske** [comment]
@ehjoon Hi,
I dynamically load libflutter_engine.so at runtime to remove a build time dependency.  The x86_64 engine artifact can be downloaded directly from google.  If you need engine for a target device then you would want to build the flutter-engine recipe found in meta-flutter layer.
1) https://github.com/meta-flutter/meta-flutter.  Automotive Grade Linux (AGL) is dependent on this layer.
2) workspace automation will download the debug x86_64 libflutter_engine.so.  This script is to setup a workstation to a known state to enable embedded linux flutter development.  If you do not want to run it, you can look at `def get_google_flutter_engine_url():`
