### ISSUE TITLE
libliftoff is not a submodule

### ISSUE THREAD

**Issue by aduskett** [toyota-connected/ivi-homescreen#139]
Building with BUILD_BACKEND_DRM or BUILD_BACKEND_WAYLAND_LEASED_DRM results in the failure:

```
CMake Error at third_party/CMakeLists.txt:116 (add_subdirectory):
  add_subdirectory given source "libliftoff-0.6.0-dev" which is not an
  existing directory.
```

It seems like libliftoff was not included as a submodule in the third_party directory

**Comment by jwinarske** [comment]
@aduskett Try a recent commit

Also note this CI job: 
https://github.com/toyota-connected/ivi-homescreen-plugins/blob/v2.0/.github/workflows/ivi-homescreen.yaml

**Comment by jwinarske** [comment]
@aduskett DRM backend support is not yet available.  Soon
