### ISSUE TITLE
Why does ivi-homescreen the fixed flutter assets path(=`/usr/local/share/homescreen`)?

### ISSUE THREAD

**Issue by WAKazuyoshiAkiyama** [toyota-connected/ivi-homescreen#2]
From my understanding, ivi-homescreen can launch the flutter aseets placed at `/usr/local/share/homescreen` only.
How can I launch multiple flutter apps with ivi-homescreen?

If ivi-homescreen accepts another flutter assets path from cmdline args like flutter-wayland(https://github.com/chinmaygarde/flutter_wayland), ivi-homescreen will become more flexible.

What do you think of this idea?

**Comment by jwinarske** [comment]
It launches from share/homescreen/bundle, which is dependent on CMAKE_INSTALL_PREFIX.  The default for CMAKE_INSTALL_PREFIX for desktop is "/usr/local", for Yocto is is "/usr".  This path is used in package install, yocto recipe install, desktop/target development workflow.  If you change this path, then all the other dependent components in developer workflow need to change.  There will some additions for command line argument support, one include screen size.
